git_repository(
    name="boringssl",
    commit="2ddb72aa77c8186391e1269442ded05bdeb0328b",
    remote="https://boringssl.googlesource.com/boringssl", )
git_repository(
    name="double_conversion",
    commit="4abe3267170fa52f39460460456990dbae803f4d",
    remote="https://github.com/google/double-conversion.git")
http_file(
    name="glog_tar",
    url="https://github.com/google/glog/archive/v0.3.4.tar.gz")
http_file(
    name="gflags_tar",
    url="https://github.com/gflags/gflags/archive/v2.2.0.tar.gz")
http_file(
    name="libunwind_tar",
    url=
    "http://download.savannah.nongnu.org/releases/libunwind/libunwind-1.1.tar.gz"
)
http_file(
    name="libevent_tar",
    url=
    "https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz"
)
http_file(
    name="boost_tar",
    url=
    "https://superb-sea2.dl.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.gz"
)
new_git_repository(
    name="google_benchmark",
    commit="3336ea00d892fc312715c3a00d33a9568261e86a",
    remote="https://github.com/google/benchmark.git",
    build_file="third_party/benchmark/benchmark.BUILD", )
new_git_repository(
    name="google_gtest",
    commit="aa148eb2b7f70ede0eb10de34b6254826bfb34f4",
    remote="https://github.com/google/googletest.git",
    build_file="third_party/gtest/gtest.BUILD",
)