package(default_visibility=["//visibility:public"])
cc_library(
    name="bits",
    hdrs=["bits.h"], )
cc_test(
    name="bits_test",
    srcs=["bits_test.cpp"],
    deps=["@google_gtest//:gtest-cxx", ":bits"],
    size="small", )
